debug = true

[trades]
instrument = "option"
currency = "BTC"
interval = "100ms"

[kafka]
broker = "kafka1:19092"
registry = "http://kafka-schema-registry:8081"
producer = { auto_offset_reset = 'earliest', topic_name = "trades-option-btc" }
