debug = true

[trades]
instrument = "option"
currency = "BTC"
interval = "100ms"

[signal]
kind = 'EWMA'
options = { period = 5 }

[kafka]
broker = "kafka1:19092"
registry = "8081"
producer = { auto_offset_reset = 'earliest', topic_name = 'EWMA_5min' }
consumer = { group_id = 'trades_options', topic_name = 'trades_option_btc' }
